name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: List Test Results Directory
        run: ls -R ./TestResults

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: './TestResults/*.trx'

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/**/coverage.cobertura.xml
          flags: unittests
          name: code-coverage

      - name: Display test results
        run: cat ./TestResults/test_results.trx
