name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Setup-Packages dependencies
          run: dotnet add package Moq
          run: dotnet add package Microsoft.EntityFrameworkCore.InMemory
          run: dotnet add package coverlet.collector
          run: dotnet add reference ../MusicRising/MusicRising.csproj 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Ensure TestResults directory exists
        run: mkdir -p $GITHUB_WORKSPACE/TestResults

      - name: Run tests
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=$GITHUB_WORKSPACE/TestResults/test_results.trx" --results-directory $GITHUB_WORKSPACE/TestResults > $GITHUB_WORKSPACE/TestResults/test_output.log 2>&1
          if [ $? -ne 0 ]; then
            echo "Test runner failed"
            cat $GITHUB_WORKSPACE/TestResults/test_output.log
            exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: $GITHUB_WORKSPACE/TestResults/test_results.trx

      - name: Upload test output log
        uses: actions/upload-artifact@v2
        with:
          name: test-output-log
          path: $GITHUB_WORKSPACE/TestResults/test_output.log

      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: $GITHUB_WORKSPACE/TestResults/**/coverage.cobertura.xml
          flags: unittests
          name: code-coverage

      - name: Display test results
        run: cat $GITHUB_WORKSPACE/TestResults/test_results.trx
